version: '3.3'

services:
    db:
      image: postgres:13.1
      environment:
        - POSTGRES_USER=$DB_USER
        - POSTGRES_PASSWORD=$DB_PASSWORD
      ports:
        - $DB_PORT:$DB_PORT
      volumes:
        - ./db/data:/var/lib/postgresql/data
        - ./db/docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
      restart: always
      command: -p $DB_PORT

    pgadmin:
      image: dpage/pgadmin4:4.18
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: $PGADMIN_EMAIL
        PGADMIN_DEFAULT_PASSWORD: $PGADMIN_PASSWORD
        PGADMIN_LISTEN_PORT: $PGADMIN_PORT
      ports:
        - "5000:80"
      volumes:
        - pgadmin-data:/var/lib/pgadmin

    node:
      depends_on:
        - db
      build:
        context: ./node
        dockerfile: Dockerfile
      environment:
        - CHOKIDAR_USEPOLLING= "true"
        - NODE_ENV=$API_NODE_ENV
        - PORT=$API_PORT
        - PGHOST=db
        - PGPORT=$DB_PORT
        - PGUSER=$DB_USER
        - PGPASSWORD=$DB_PASSWORD
        - PGDATABASE=$DB_NAME
        - JWT_ALGO=$JWT_ALGO
        - API_ROUTE=$API_ROUTE
        - USER=$USER
        - FRIENDS=$FRIENDS
        - CODE=$CODE
        - LOCATION=$LOCATION
        - AUTHORIZED=$AUTHORIZED
        - AUDIENCE=$REACT_APP_AUDIENCE
        - DOMAIN=$REACT_APP_AUTH0_DOMAIN
      ports:
        - $API_PORT:$API_PORT
      volumes:
        - /app/node_modules
        - ./node:/app
        - ./logs:/root/.npm/_logs/
      stdin_open: true

    react:
        build:
            context: ./react
            dockerfile: Dockerfile
        environment:
          - CHOKIDAR_USEPOLLING= "true"
          - REACT_APP_AUTH0_DOMAIN=$REACT_APP_AUTH0_DOMAIN
          - REACT_APP_AUTH0_CLIENT_ID=$REACT_APP_AUTH0_CLIENT_ID
          - REACT_APP_AUDIENCE=$REACT_APP_AUDIENCE
          - REACT_APP_API_BASE_URL=$REACT_APP_API_BASE_URL
          - REACT_APP_API_USERS_ENDPOINT=$REACT_APP_API_USERS_ENDPOINT
          - REACT_APP_API_LOCATION_ENDPOINT=$REACT_APP_API_LOCATION_ENDPOINT
          - REACT_APP_API_FRIENDS_ENDPOINT=$REACT_APP_API_FRIENDS_ENDPOINT
          - REACT_APP_API_LOCATION_ACCESS_TOKEN=$REACT_APP_API_LOCATION_ACCESS_TOKEN
        ports:
          - $UI_PORT:$UI_PORT
        volumes:
          - ./react:/app
          - /app/node_modules
        stdin_open: true
volumes:
    db-data:
    pgadmin-data:

